### PR TITLE
Fixes #87: Do not cache search results if regular expression contains \G

### LINKED ISSUE #87: Searches should not be cached for regular expressions that use \G
Extracted from https://github.com/Microsoft/vscode-textmate/issues/70

Currently, when using the same instance of an `OnigString`, search results for regular expressions are cached. This is an important feature that allows this library to be used to tokenize long lines quickly and it works great most of the time.

However, there are certain regular expressions for which caching should not be used. Namely, those that use the anchor `\G` (documented [here](https://github.com/kkos/oniguruma/blob/05b857587c9d61ef4b37fe9984c2fd9c0b03fd1b/doc/RE#L159)). The `\G` pattern targets the current search location and we therefore cannot cache one search result with a certain search location and reuse that result with a different search location.

Here is an example:
```js
let str = new OnigString('first-and-second');
let scanner = new OnigScanner(['\\G-and'])
let match = scanner.findNextMatchSync(str, 0)
expect(match).toEqual(null)
// When searching from position 0, `\G-and` does not match
// This is correct, but this ends up being cached and this result
// will be incorrectly returned below

match = scanner.findNextMatchSync(str, 5)
// Here, the regex should be found because the string 'first-and-second'
// does match '\G-and' at position 5.
// currently, this returns the cached result from above (null)
```

I will submit a PR in a couple minutes.

(fyi @daviwil @maxbrunsfeld)

### PR DESCRIPTION
**Pull request by alexandrudima**
See #87

* Disables caching if the regular expression contains `\G`.
* Adds a regression test.

(fyi @daviwil @maxbrunsfeld)

### CODE REVIEW

File: src/onig-reg-exp.cc [hunk 1]
```diff
@@ -10,6 +10,17 @@ OnigRegExp::OnigRegExp(const string& source)
...
+  for (size_t pos = 0, len = source.size(); pos < len; pos++) {
+    if (source[pos] == '\\' && pos + 1 < len) {
+      if (source[pos + 1] == 'G') {
+        hasGAnchor = true;
+        break;
+      }
+      pos++;
+    }
+  }
+
```
Comment (maxbrunsfeld) [inline src/onig-reg-exp.cc]: I think this could be written using [`std::string::find`](http://www.cplusplus.com/reference/string/string/find/), which should be faster for long regular expressions:

```cpp
hasGAnchor = source.find("\\G") != string::npos;
```

Comment (alexandrudima) [reply src/onig-reg-exp.cc]: :+1: for the speed benefit, but would that not fall for an escaped backslash followed by G?

e.g. `\\Ghello` vs `\Ghello`. The first is literally looking for `\Ghello`, while the second is looking for `hello` if the search position is right before `h`.

Comment (maxbrunsfeld) [reply src/onig-reg-exp.cc]: Ah, of course; I didn't notice that you were actually accounting for that case here.

**Comment by maxbrunsfeld** [comment]
This change is in v7.0.2.
